Joinee-IM/frontend

- .vscode/settings.json
- README.md
- src/components/Button/RippleButton.tsx
- src/main.tsx
- src/modules/entry/components/Cover.tsx
- src/provider/theme/index.tsx
- src/provider/theme/styled.d.ts
- src/provider/theme/theme.ts
> feat(app): initialize theming

- .github/workflows/cd.yml
- deploy/helm/charts/.helmignore
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/NOTES.txt
- deploy/helm/charts/templates/_helpers.tpl
- deploy/helm/charts/templates/deployment.yaml
- deploy/helm/charts/templates/hpa.yaml
- deploy/helm/charts/templates/ingress.yaml
- deploy/helm/charts/templates/service.yaml
- deploy/helm/charts/templates/serviceaccount.yaml
- deploy/helm/charts/templates/tests/test-connection.yaml
- deploy/helm/production/values.yaml
- docker/DockerFile
- docker/nginx.conf
- env/.env.development
- env/.env.production
- src/constants/env.ts
- src/modules/auth/service/index.ts
> feat(k8s): configure deployment

- .github/workflows/cd.yml
> feat(cd): modify github action target branch

- src/modules/auth/pages/forgetPassword/ResetPassword.tsx
- src/modules/auth/pages/forgetPassword/SendMail.tsx
- src/modules/auth/pages/forgetPassword/index.tsx
- src/modules/auth/pages/signup/SendMail.tsx
- src/modules/auth/pages/signup/index.tsx
- src/modules/main/pages/UserInfo/BaseInfoSection.tsx
- src/modules/main/pages/UserInfo/SecuritySection.tsx
> fix(button loading ): fix button loading

- .github/workflows/cd.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
> fix(devops): resolve google api key error

- docker/DockerFile
> fix(k8s): add env into dockerfile

- docker/DockerFile
> fix(k8s): move env to earlier stage

- .github/workflows/cd.yml
- docker/DockerFile
> fix(k8s): use build-arg in DockerFile, modify cd.yml

- .github/workflows/cd.yml
- docker/DockerFile
> Release 2023.12.14 fix Dockerfile env

- src/contexts/useUser.tsx
- src/modules/main/components/Header.tsx
- src/modules/main/index.tsx
- src/modules/main/pages/Reserve/index.tsx
- src/utils/function/date.ts
> fix(reservation): create reservation

- src/components/Loading/RippleLoading.tsx
- src/components/TimeSlot/index.tsx
> fix(loading): z-index down to earth

- src/modules/lessor/pages/Upload/Stadium.tsx
- src/services/type.ts
> Release Integration

- src/components/Loading/RippleLoading.tsx
- src/components/TimeSlot/index.tsx
- src/modules/main/pages/Stadium/index.tsx
- src/services/type.ts
> chore(component): naming

- src/components/Loading/RippleLoading.tsx
- src/components/TimeSlot/index.tsx
- src/modules/main/pages/Stadium/index.tsx
- src/services/type.ts
> Release: 2023.12.15 integration

- src/provider/theme/antd.config.tsx
> style(switch color): change switch color

- src/components/Button/RippleButton.tsx
- src/constants/module.ts
- src/modules/history/index.tsx
- src/modules/lessor/pages/Venue.tsx
- src/modules/main/pages/Partner/components/FlipCard.tsx
- src/modules/main/pages/Reserve/components/Action.tsx
- src/modules/main/pages/Reserve/hooks/useData.tsx
- src/modules/main/pages/Reserve/index.tsx
- src/modules/main/pages/Reserve/services/index.ts
- src/modules/main/pages/Venue/index.tsx
- src/services/type.ts
> fix(reservation): fix appearance after creating reservation

- src/components/FlipCard.tsx
- src/modules/main/pages/Partner/components/FlipCard.tsx
> fix(partner): fix user flow of partner

- src/modules/lessor/pages/Upload/Stadium.tsx
> fix(create stadium): fix navigate after create stadium

- src/hooks/useSorter.ts
- src/modules/main/pages/Venue/List.tsx
> fix(venue): add sorter in filter bar

- src/modules/main/pages/Stadium/components/DetailModal.tsx
- src/modules/main/pages/Stadium/components/ListItem.tsx
- src/utils/function/time.ts
> fix(time): fix business hour for stadium

- src/modules/main/pages/Partner/index.tsx
- src/services/type.ts
> fix(seek for player): fix vacancy problem

- src/assets/icons/CloseWithBackground.tsx
- src/hooks/useSorter.ts
- src/modules/lessor/pages/Venue.tsx
- src/modules/main/pages/Reserve/hooks/useData.tsx
- src/modules/main/pages/Stadium/components/DetailModal.tsx
- src/modules/main/pages/Venue/components/ListItem.tsx
- src/modules/main/pages/Venue/index.tsx
- src/provider/theme/antd.config.tsx
- src/utils/function/map/toMemberStatus.tsx
- src/utils/function/map/toTechnicalLevel.ts
> fix(app): fix multiple bugs

- src/assets/icons/CloseWithBackground.tsx
- src/components/Title.tsx
- src/hooks/useSorter.ts
- src/modules/entry/components/Cover.tsx
- src/modules/lessor/pages/Venue.tsx
- src/modules/main/pages/Partner/index.tsx
- src/modules/main/pages/Reserve/hooks/useData.tsx
- src/modules/main/pages/Stadium/components/DetailModal.tsx
- src/modules/main/pages/Venue/components/ListItem.tsx
- src/modules/main/pages/Venue/index.tsx
- src/provider/theme/antd.config.tsx
- src/services/type.ts
- src/utils/function/map/toMemberStatus.tsx
- src/utils/function/map/toTechnicalLevel.ts
> Release: 2023.12.18

- deploy/helm/production/values.yaml
> chore(k8s): specify resource limit

- src/index.css
- src/modules/auth/components/Card.tsx
- src/modules/auth/pages/signup/Role.tsx
- src/modules/lessor/pages/Manage/Court.tsx
- src/modules/lessor/pages/Manage/Stadium.tsx
- src/modules/lessor/pages/Manage/Venue.tsx
- src/modules/lessor/pages/Manage/index.tsx
- src/modules/main/components/Filter.tsx
- src/modules/main/components/Header.tsx
- src/modules/main/pages/Venue/List.tsx
- src/provider/theme/antd.config.tsx
> fix: UI adjustment

- deploy/helm/production/values.yaml
> chore(k8s): use ClusterIP

- src/provider/theme/antd.config.tsx
> fix(antd-style): adjust style of textfield and select

- src/assets/icons/SeekForPlayer.tsx
- src/components/Tag.tsx
- src/components/TimeSlot/index.tsx
- src/modules/lessor/pages/Manage/Court.tsx
- src/modules/lessor/pages/Manage/Stadium.tsx
- src/modules/lessor/pages/Manage/Venue.tsx
- src/modules/main/components/Filter.tsx
- src/modules/main/pages/Partner/index.tsx
- src/modules/main/pages/Venue/index.tsx
- src/provider/theme/theme.ts
- src/utils/function/time.ts
> fix(timeslot): fix available timeslot

- src/components/TimeSlot/index.tsx
- src/components/TimeSlot/useTimeSlotDrag.ts
- src/constants/module.ts
- src/modules/lessor/pages/Manage/Court.tsx
- src/modules/lessor/pages/Manage/Stadium.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/main/pages/Detail/index.tsx
- src/modules/main/pages/Reserve/index.tsx
- src/routes/main/manage/[account_id]/venue/[venue_id].tsx
> fix(provider): resolve provider issues

- src/assets/icons/SeekForPlayer.tsx
- src/components/Tag.tsx
- src/components/TimeSlot/index.tsx
- src/components/TimeSlot/useTimeSlotDrag.ts
- src/constants/module.ts
- src/modules/lessor/pages/Manage/Court.tsx
- src/modules/lessor/pages/Manage/Stadium.tsx
- src/modules/lessor/pages/Manage/Venue.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/main/components/Filter.tsx
- src/modules/main/pages/Detail/index.tsx
- src/modules/main/pages/Partner/index.tsx
- src/modules/main/pages/Reserve/index.tsx
- src/modules/main/pages/Venue/index.tsx
- src/provider/theme/theme.ts
- src/routes/main/manage/[account_id]/venue/[venue_id].tsx
- src/utils/function/time.ts
> Release 2023.12.20 for Provider Issues

- src/modules/main/pages/Venue/index.tsx
> fix(reservation info): fix court id

- src/components/Button/theme.ts
- src/constants/routePath.ts
- src/hooks/useError.ts
- src/modules/lessor/pages/Manage/Stadium.tsx
- src/modules/lessor/pages/Upload/Court.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/lessor/pages/Upload/Venue.tsx
- src/modules/lessor/pages/Upload/services/index.ts
- src/modules/main/components/Header.tsx
- src/routes/main/manage/[account_id]/create/court.tsx
- src/routes/main/manage/[account_id]/create/venue.tsx
- src/routes/main/manage/[account_id]/index.tsx
> feat(manager): implement uploading stadiums and vourts

- src/modules/main/pages/Venue/index.tsx
> fix(venue): resolve ui adjuestment

- src/components/TimeSlot/index.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/main/pages/Detail/index.tsx
- src/modules/main/pages/Reserve/components/Action.tsx
- src/modules/main/pages/UserInfo/index.tsx
- src/modules/main/pages/Venue/List.tsx
- src/modules/main/pages/Venue/index.tsx
- src/utils/function/time.ts
> feat(create-stadium): implement modal timeslot

- src/modules/lessor/pages/Manage/index.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/lessor/pages/Upload/Venue.tsx
- src/modules/lessor/services/index.ts
- src/modules/main/pages/Detail/index.tsx
- src/modules/main/pages/Venue/index.tsx
> fix(venue info page): fix bugs of venue info page

- src/constants/routePath.ts
- src/modules/main/pages/Reserve/Code.tsx
- src/modules/main/pages/Reserve/components/Action.tsx
- src/modules/main/pages/Reserve/services/index.ts
- src/routes/main/index.tsx
- src/routes/main/reservation/code/[code].tsx
- src/services/type.ts
> feat(invitation code): implement code for reservaion

- src/hooks/useSorter.ts
- src/modules/main/pages/Partner/index.tsx
> fix(patner): filter

- src/modules/lessor/pages/Manage/Venue.tsx
- src/modules/lessor/pages/Manage/index.tsx
- src/modules/main/pages/Venue/List.tsx
- src/utils/function/map/toFeeType.ts
- src/utils/function/money.ts
> fix(table-mamangement): filter

- src/modules/lessor/pages/Manage/Stadium.tsx
> fix(manage stadium page): remove unclickable right arrow

- src/components/TimeSlot/index.tsx
- src/constants/routePath.ts
- src/hooks/useSorter.ts
- src/modules/lessor/pages/Manage/Stadium.tsx
- src/modules/lessor/pages/Manage/Venue.tsx
- src/modules/lessor/pages/Manage/index.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/lessor/pages/Upload/Venue.tsx
- src/modules/lessor/services/index.ts
- src/modules/main/pages/Detail/index.tsx
- src/modules/main/pages/Partner/index.tsx
- src/modules/main/pages/Reserve/Code.tsx
- src/modules/main/pages/Reserve/components/Action.tsx
- src/modules/main/pages/Reserve/services/index.ts
- src/modules/main/pages/UserInfo/index.tsx
- src/modules/main/pages/Venue/List.tsx
- src/modules/main/pages/Venue/index.tsx
- src/routes/main/index.tsx
- src/routes/main/reservation/code/[code].tsx
- src/services/type.ts
- src/utils/function/map/toFeeType.ts
- src/utils/function/money.ts
- src/utils/function/time.ts
> Release: 2023.12.21

- src/components/TimeSlot/index.tsx
- src/modules/lessor/pages/Upload/Stadium.tsx
- src/modules/main/pages/Stadium/index.tsx
> fix(erica): fix priority

- src/modules/main/pages/Partner/index.tsx
- src/modules/main/pages/Reserve/components/Action.tsx
- src/modules/main/pages/Reserve/services/index.ts
- src/services/type.ts
> Release 2023.12.21 for reservstion page
